### ISSUE TITLE
convince to use separately-packaged qdldl

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/osqp-feedstock#3]
Would be nicer, if only for bot purposes, if we could install `qdldl` separately and have `osqp` use that (instead of having to source the submodule as in https://github.com/conda-forge/osqp-feedstock/pull/2). Should look into patching to allow for that.

**Comment by dougalsutherland** [comment]
@bstellato If you have suggestions about this, by the way, that would be nice. Does it make sense for `osqp` to support using a global `libqdldl` install instead of building it itself?

**Comment by bstellato** [comment]
I think it would make lots of things easier if we required only the shared qdldl libraries. Unfortunately, there is a big part related to code generation that would require anyway to have the qdldl sources ready in the same folder as the python package. Note that we are also maintaining pip wheels which would also need a significant change in both the python interface and the packaging if we want to separate osqp and qdldl. 

I believe the current solution is not ideal but it is a decent compromise. What do you think? @goulart-paul @gbanjac?

**Comment by dougalsutherland** [comment]
Oh, for wheels it totally makes sense to have a qdldl "inline." I was talking about as an option. :)

Does the code generation need the actual sources or just the headers from `include`? If it needs the actual source, then it doesn't really help with our (small but mildly annoying) infrastructure problem anyway.
